import type { Metadata } from "next";
import { Fredoka, Nunito } from "next/font/google";
import "./globals.css";

// Display face — chunky, rounded, storybook. Used only for Amelia's name.
const fredoka = Fredoka({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// Body / utility face — rounded, highly legible.
const nunito = Nunito({
  variable: "--font-body",
  subsets: ["latin"],
});

const SITE_URL = "https://amelialass.com";
const title = "Amelia — coming soon";
const description =
  "A playful little website for Amelia is on its way — birthday adventures, wish lists, and more.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title,
  description,
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Amelia",
    title,
    description,
    // OG image generated by src/app/opengraph-image.tsx (1200×630)
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
  // Placeholder site — keep it out of search results until launch.
  robots: { index: false, follow: false },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${fredoka.variable} ${nunito.variable} h-full antialiased`}
    >
      <body className="flex min-h-dvh flex-col bg-[var(--color-bg)] text-[var(--color-ink)]">
        {children}
      </body>
    </html>
  );
}
